services:
  db:
    env_file: .env
    image: postgres:15.1-alpine3.17
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: sinder-db

  sinder:
    env_file: .env
    build: .
    container_name: sinder
    depends_on:
      - db
      - minio

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - sinder
    volumes:
      - ./conf:/etc/nginx/conf.d
    ports:
      - 80:80
    links:
      - sinder
      - minio

  minio:
    env_file: .env
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data/
    volumes:
      - minio-data:/data

volumes:
  minio-data:
      driver: local
  postgres-data:
      driver: local
