services:
  db:
    env_file:
      - .env
    image: 'postgres:15.1-alpine3.17'
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: db

  sinder:
    env_file:
      - .env
    build: .
    ports:
      - '8081:8080'
    container_name: sinder
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
