spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  minio:
    bucket: ${MINIO_DEFAULT_BUCKETS}
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
    url: ${SPRING_MINIO_URL}
  jackson:
    default-property-inclusion: NON_NULL

sinder:
  security:
    access-key: ${SINDER_SECRETS_ACCESS-KEY}
    refresh-key: ${SINDER_SECRETS_REFRESH-KEY}
    enable-key: ${SINDER_SECRETS_ENABLE-KEY}
    password-refresh-key: ${SINDER_SECRETS_PASSWORD-REFRESH-KEY}
    access-expiration-time: ${SINDER_SECRETS_ACCESS-EXPIRATION-TIME}
    refresh-expiration-time: ${SINDER_SECRETS_REFRESH-EXPIRATION-TIME}

  mail:
    host: ${SINDER_MAIL_HOST}
    username: ${SINDER_MAIL_USERNAME}
    password: ${SINDER_MAIL_PASSWORD}
    port: ${SINDER_MAIL_PORT}
    protocol: ${SINDER_MAIL_PROTOCOL}

springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /api/v1/swagger-ui
