spring:
  config:
    import: .env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      schema: sinder
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: sinder

sinder:
  security:
    access-key: ${SINDER_SECRETS_ACCESS-KEY}
    refresh-key: ${SINDER_SECRETS_REFRESH-KEY}
    enable-key: ${SINDER_SECRETS_ENABLE-KEY}
    password-refresh-key: ${SINDER_SECRETS_REFRESH-PASSWORD-KEY}
    access-expiration-time: 3600
    refresh-expiration-time: 604800
  mail:
    host: ${SINDER_MAIL_HOST}
    username: ${SINDER_MAIL_USERNAME}
    password: ${SINDER_MAIL_PASSWORD}
    port: ${SINDER_MAIL_PORT}
    protocol: ${SINDER_MAIL_PROTOCOL}
